cpp:
	g++ hello-world.cpp -o hello-world.out

wasm:
	em++ hello-world.cpp -o hello-world.html

serve:
	emrun ./hello-world.html

clean:
	rm -f hello-world.out hello-world.js hello-world.html hello-world.wasm
